project_founder_and_manager = "Anish Mishra"
authors = [
  "Anish Mishra (syntaxerror247)"
]

donors = []
anonymous_donors = 0
golden_donors = []
anonymous_golden_donors = 0

diamond_donors = []
anonymous_diamond_donors = 0

past_donors = []
past_anonymous_donors = 0
past_golden_donors = []
past_anonymous_golden_donors = 0
past_diamond_donors = []
past_anonymous_diamond_donors = 0
